// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi4ewjngTwamsbtI0wOfoxsPDsBuz8-jU',
    appId: '1:829601661680:android:dd0e206c59892c44167835',
    messagingSenderId: '829601661680',
    projectId: 'teste-firebase-67c93',
    databaseURL: 'https://teste-firebase-67c93.firebaseio.com',
    storageBucket: 'teste-firebase-67c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5KoIrAiNe4KBhBTijRnm69tKf2F5p-oI',
    appId: '1:829601661680:ios:4cabb837959e874a167835',
    messagingSenderId: '829601661680',
    projectId: 'teste-firebase-67c93',
    databaseURL: 'https://teste-firebase-67c93.firebaseio.com',
    storageBucket: 'teste-firebase-67c93.appspot.com',
    iosBundleId: 'me.carda.awesomeNotificationsFcmExample.AwesomeNotificationService',
  );

}